# Generated by Django 4.1.2 on 2022-12-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lid', models.EmailField(max_length=50, verbose_name='Email')),
                ('Laboratorypwd', models.CharField(max_length=20, verbose_name='Password')),
                ('Laboratoryfname', models.CharField(default='', max_length=20, verbose_name='Laboratory_Name')),
                ('Laboratorymname', models.CharField(default='', max_length=20, verbose_name='First_Name')),
                ('Laboratorylname', models.CharField(default='', max_length=20, verbose_name='Last_Name')),
                ('Laboratoryaddress', models.CharField(default='', max_length=20, verbose_name='Address')),
                ('Laboratorycity', models.CharField(default='', max_length=20, verbose_name='City')),
                ('Laboratoryarea', models.CharField(default='', max_length=20, verbose_name='Area')),
                ('Laboratorypincode', models.IntegerField(default='', verbose_name='Pincode')),
                ('Laboratorycontactno', models.IntegerField(default='', verbose_name='Contact_No')),
                ('Laboratoryphoto', models.FileField(upload_to='upload', verbose_name='Laboratory certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Name_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=200, verbose_name='Blood Test Name')),
            ],
        ),
        migrations.CreateModel(
            name='Reference_Test_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Haemoglobin_reference', models.TextField(default='male : 14 - 16g \n Female : 12 - 14 g')),
                ('RBC_reference', models.TextField(default='14 - 16g%')),
                ('PCV_reference', models.TextField(default='35 - 45 %')),
                ('MCV_reference', models.TextField(default='80 - 99 fl')),
                ('MCH_reference', models.TextField(default='28 - 32 pg')),
                ('MCHC_reference', models.TextField(default='30 - 34 %')),
                ('RDW_reference', models.TextField(default='9 - 17 fl')),
                ('Total_WBC_Count_reference', models.TextField(default='4000 - 11000 / cu.mm')),
                ('Neutrophils_reference', models.TextField(default='40 - 75 %')),
                ('Lymphocytes_reference', models.TextField(default='20 - 45 %')),
                ('Eosinophils_reference', models.TextField(default='00 - 06 %')),
                ('Monocytes_reference', models.TextField(default='00 - 10 %')),
                ('Basophils_reference', models.TextField(default='00 - 01 %')),
                ('Platelet_Count_reference', models.TextField(default='150000 - 450000 / cu.mm')),
            ],
        ),
        migrations.CreateModel(
            name='Test_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_test', models.DateField(auto_created=True, auto_now=True)),
                ('Test_name', models.CharField(default='', max_length=200, verbose_name='Blood Test Name')),
                ('patientname', models.CharField(default='', max_length=200, verbose_name='Patient Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('Haemoglobin', models.PositiveIntegerField(default='')),
                ('RBC_Count', models.PositiveIntegerField(default='')),
                ('PCV', models.PositiveIntegerField(default='')),
                ('MCV', models.PositiveIntegerField(default='')),
                ('MCH', models.PositiveIntegerField(default='')),
                ('MCHC', models.PositiveIntegerField(default='')),
                ('RDW', models.PositiveIntegerField(default='')),
                ('Total_WBC_Count', models.PositiveIntegerField(default='')),
                ('Neutrophils', models.PositiveIntegerField(default='')),
                ('Lymphocytes', models.PositiveIntegerField(default='')),
                ('Eosinophils', models.PositiveIntegerField(default='')),
                ('Monocytes', models.PositiveIntegerField(default='')),
                ('Basophils', models.PositiveIntegerField(default='')),
                ('Platelet_Count', models.PositiveIntegerField(default='')),
                ('WBCs_on_PS', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('schedule', models.DateTimeField()),
                ('appointment_booked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=12)),
                ('Test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoryapp.name_category')),
            ],
        ),
    ]
