# Generated by Django 4.1.2 on 2023-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0002_test_category_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_category',
            name='lab_name',
            field=models.CharField(default='', max_length=200, verbose_name='Lab Name'),
        ),
        migrations.AlterField(
            model_name='test_category',
            name='l_name',
            field=models.CharField(default='', max_length=200, verbose_name='Lab Assistance Name'),
        ),
    ]
